### ISSUE TITLE
Broken link on README

### ISSUE THREAD

**Issue by simonthelwall** [gasparrini/2017_lopezbernal_IJE_codedata#1]
The link (below) to the full text of the paper is broken and returns a 404 error, please could this be updated?
http://www.ag-myresearch.com/2016_lopezbernal_ije.html

**Comment by simonthelwall** [comment]
Original article is open access so could use this?
[IJE link](https://academic.oup.com/ije/article/46/1/348/2622842)

**Comment by gasparrini** [comment]
Thanks, Simon.

The issues was due to a change in the url after the final publication of the manuscript.

See http://www.ag-myresearch.com/2017_lopezbernal_ije.html.


Best

-Antonio Gasparrini


________________________________

**Comment by simonthelwall** [comment]
Thanks very much
